[ngsi]
  # Location of the NGSI-LD endpoint
  host = "http://localhost:9090/ngsi-ld/v1"

[api]
  # Base URI of the generated fragments
  host = "http://localhost:3001"
  # time range (last number of minutes) to include in the /latest fragments
  lastNumberOfMinutes = 100
  # Use NGSI metadata model or simplified keyValues
  keyValues = true

[data]
  # NGSI-LD exclusively uses relative property URIs
  # These are resolved using the active context
  # Relative URIs used as objects (in JSON-LD) are considered relative to the base URI instead
  # This is a list of such properties that need to be made absolute when needed
  metrics = ["NO2", "O3", "PM10", "PM1", "PM25"]